main_page/urls.py
from django.urls import path
from . import views

app_name = "main_page"
urlpatterns = [
    path('', views.MainPageView.as_view(), name="main_page_view"),
    path('download-cv/', views.download_cv, name='download_cv')
]

portfolio_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_page/models.py
from django.db import models

# Create your models here.
class Technologies(models.Model):
    name = models.CharField(max_length=20, null=True)
    

    class Meta:
        verbose_name_plural = "Technologies"


    def __str__(self):
        return self.name


class Projects(models.Model):
    name = models.CharField(max_length=30)
    link = models.URLField(unique=True)
    project_image = models.ImageField()
    technologies = models.ManyToManyField(Technologies)


    class Meta:
        verbose_name_plural = "Projects"

    
    def __str__(self):
        return self.name


class RecievedMessages(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

main_page/forms.py
from django import forms
from .models import RecievedMessages

class ReceivedMessagesForm(forms.ModelForm):
    class Meta:
        model = RecievedMessages
        fields = '__all__'


class ReceivedMessagesSpanishForm(forms.ModelForm):
    class Meta:
        model = RecievedMessages
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = "Nombre"
        self.fields['message'].label = "Mensaje"

main_page/views.py
import mimetypes
import os
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.templatetags.static import static
from .models import Projects
from .forms import ReceivedMessagesForm, ReceivedMessagesSpanishForm
# Create your views here.

class MainPageView(View):
    def get(self, request):
        language = request.GET.get('lan') if request.GET.get('lan') else 'es'
        if language == 'es':
            context = {
                'projects': Projects.objects.all(),
                'contact_form': ReceivedMessagesSpanishForm()
            }
            return render(request, 'main_page/main_page_spanish.html', context)
        else:
            context = {
                'projects': Projects.objects.all(),
                'contact_form': ReceivedMessagesForm()
            }
            return render(request, 'index.html', context)
    
    def post(self, request):
        language = request.GET.get('lan') if request.GET.get('lan') else 'en'
        if language == 'es':
            form = ReceivedMessagesSpanishForm(request.POST)
        else:
            form = ReceivedMessagesForm(request.POST)
        if form.is_valid():
            form.save()
            if language == 'es':
                form = ReceivedMessagesSpanishForm()
            else:
                form = ReceivedMessagesForm()
            response_data = {
                'result': 'success',
                'form_html': render_to_string('main_page/includes/contact_form.html', {'form': form, 'lan': language})
            }
            return JsonResponse(response_data)
        response_data = {
            'error': 'error',
            'message': 'Form invalid',
            'form_html': render_to_string('main_page/includes/contact_form.html', {'form': form})
        }
        response = JsonResponse(response_data)
        response.status_code = 403 # The message couln't be published and return error to ajax code with form data
        print(response)
        return response


def download_cv(request):
    language = request.GET.get('lan')
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    filename = 'CV-Gregori-Azuaje-Cabanerio-english.pdf' if language == 'en' else 'CV-Gregori-Azuaje-Cabanerio-spanish.pdf'
    filepath = BASE_DIR + '/static/' + filename
    print(BASE_DIR)
    path = open(filepath, 'rb')
    mime_type, _ = mimetypes.guess_type(filepath)
    print(mime_type)
    response = HttpResponse(path, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

main_page/templates/main_page/includes/contact_form.html
{% load crispy_forms_tags %}


{{ form|crispy }}
<div id="form-send-output"></div>
{% if lan == 'es' %}   
    <button type=submit class="btn btn-success my-3" id="form-button">Enviar mensaje</button>
{% else %}
    <button type=submit class="btn btn-success my-3" id="form-button">Send message</button>
{% endif %}

main_page/templates/main_page/main_page_spanish.html
{% extends 'index.html' %}

{% block titulo %}Gregori Azuaje | desarrollador web backend{% endblock titulo %}

{% block navbar_menu_work %}Desarrollador backend Django{% endblock navbar_menu_work %}

{% block navbar_about_expanded %}Sobre mí{% endblock navbar_about_expanded %}

{% block navbar_portfolio_expanded %}Portafolio{% endblock navbar_portfolio_expanded %}

{% block navbar_skills_expanded %}Habilidades{% endblock navbar_skills_expanded %}

{% block navbar_contact_expanded %}Contacto{% endblock navbar_contact_expanded %}

{% block navbar_about %}Sobre mí{% endblock navbar_about %}

{% block navbar_portfolio %}Portafolio{% endblock navbar_portfolio %}

{% block navbar_skills %}Habilidades{% endblock navbar_skills %}

{% block navbar_contact %}Contacto{% endblock navbar_contact %}

{% block about_header %}Sobre mí{% endblock about_header %}

{% block about_info_header %}Desarrollador backend Django y programador software con Python{% endblock about_info_header %}

{% block about_info %}
Soy un programador y crypto trader con más de 1 año de experiencia programando en Python y actualmente dedicado
al desarrollo web a través de Django, mi área principal en el desarrollo web está enfocada en el backend,
sin embargo también poseo algunos conocimientos en CSS3 y Javascript<br><br>

Mi objetivo principal es especializarme en el lenguaje de programación python, sin embargo ya que soy un amante 
de la programación en si misma estoy más que dispuesto a aprender y trabajar con cualquier otra tecnología que
me permita crecer en el campo del desarrollo web y desarrollo de software
{% endblock about_info %}

{% block download_cv_button %}
  <a href="{% url 'main_page:download_cv' %}?lan=es" class='btn btn-danger btn-outline-dark text-white'>Descargar CV</a>
{% endblock download_cv_button %}


{% block portfolio_header %}Portafolio{% endblock portfolio_header %}

{% block techs_used_text %}Tecnologías usadas:{% endblock techs_used_text %}

{% block project_link_text %}Ir al sitio{% endblock project_link_text %}

{% block skillset_header %}Habilidades{% endblock skillset_header %}

{% block contact_header %}Contacto{% endblock contact_header %}

{% block contact_form %}
<form action="{% url 'main_page:main_page_view'%}?lan=es" class="needs-validation" method="POST" id="contact-form">
  {% csrf_token %}
  <div id="form_fields">
      {% include "main_page/includes/contact_form.html" with form=contact_form %}
  </div>
</form>
{% endblock contact_form %}

{% block footer_span %}Diseñado y desarrollado por Gregori Azuaje Cabanerio &copy;2022. Todos los derechos reservados{% endblock footer_span %}

{% block form_submit_ajax_validation %}
<script>
    $('#contact-form').on('submit', function(e) {
        $('#form-button').addClass('disabled');
        e.preventDefault();
      
        $.ajax({
          type : 'POST',
          url : '{% url "main_page:main_page_view"%}?lan=es',
          data: {
              name: $("#id_name").val(),
              email: $('#id_email').val(),
              message: $('#id_message').val(),
              csrfmiddlewaretoken: '{{ csrf_token }}',
              dataType: "json"
          },
          success: function(result, status, xhr){
            $('#form_fields').html(result.form_html)
            $("#form-send-output").html("Tu mensaje ha sido enviado, me pondré en contacto contigo lo más pronto posible")
            .addClass("text-success fs-5");
          },
          error: function(xhr, status, error){
            $("#form_fields").html(xhr.responseJSON.form_html)
            $("#form-send-output").html("Ha habido un problema al enviar tus mensajes, por favor revisa que todos los campos estén llenos y vuelve a intentar")
            .addClass("text-danger fs-5")
          }
        });
      });
</script>
{% endblock form_submit_ajax_validation %}